package main

/* KNOWN ISSUES: USING ORIGINAL 3D COORDINATES FROM BRAIN2MESH CAUSES THE
 * PLANE GENERATION TO BREAK. STARTUP TAKES TOO LONG; SHOULD LOAD
 * TARGET TETRAHEDRONS FROM JSON FILE GENERATED BY PYTHON, INSTEAD OF 
 * FINDING THEM AT STARTUP. GROUPS OF 4 POINTS FROM SCRIPT ARE OUT OF
 * ORDER.
 * ARE THEY ALL OUT OF ORDER IN THE SAME WAY?
 */

import (
	"log"
	"net/http"
	"./web"
	"./algorithm"
	"./graph"
)

var numCPU = 8

func main(){
	//startUp()
	graph := graph.NewGraph(numCPU)
	algorithm.Start(graph)
	http.Handle("/", http.FileServer(http.Dir("./app")))
	http.HandleFunc("/getSelectionSlice", web.SelectionSliceRequestHandler)
	http.HandleFunc("/getPlane", web.PlaneRequestHandler)
	http.HandleFunc("/getZRange", web.GetZRangeRequestHandler)
	http.HandleFunc("/searchPlanes", web.SearchSpaceRequestHandler)
	log.Println("Listening on port 8080...")
	log.Fatal(http.ListenAndServe(":8080", nil))
}